Mark out file
rwth-i6/i6_core pull request #155
Opened 2021-10-01 15:17 UTC by mattiadg

This job wasn't included in the renaming

2021-10-01 15:33 UTC, michelwi requested changes
Please also change the name where it is used. I found these positions:
https://github.com/rwth-i6/i6_core/blob/0ca5462aa8ff7650390674a6c44a977128cedf85/meta/system.py#L425
https://github.com/rwth-i6/i6_core/blob/34f82dd09f932da9d6c28d9781d7f20d4df888af/corpus/costa.py#L51

2021-10-01 15:49 UTC, mattiadg commented
I didn't find other usages but I've found another class with exactly the same problem

2021-10-01 15:53 UTC, michelwi approved these changes
There are some more classes with this problem (cf. https://github.com/rwth-i6/i6_core/search?q=log_file), but these two seem to be corrected consistently.

2021-10-05 10:15 UTC, curufinwe approved these changes

2021-10-05 10:16 UTC, merged