Add pro and epilog to rasr config
rwth-i6/i6_core pull request #192
Opened 2021-11-30 13:45 UTC by Nintendo-Wei

2021-11-30 17:03 UTC, curufinwe requested changes

2021-11-30 17:03 UTC, curufinwe commented on rasr/config.py
> +        buf.append(self._epilog)
same as with prolog

2021-11-30 17:03 UTC, curufinwe commented on rasr/config.py
> +    def _sis_hash(self):
This is probably not right. Now the config values themselves are not hashed. Also it is essential that old hashes do not change after the addition of prolog/epilog.

2021-11-30 17:09 UTC, michelwi requested changes

2021-11-30 17:09 UTC, michelwi commented on rasr/config.py
> +    def _sis_hash(self):
Will this not ignore the regular contents of the config? Or is it complementary to the `__sis_state__` ?

Also, to preserve the hashes of older configs, if the value is `""` it should be excluded from the hash.

2021-12-01 11:36 UTC, michelwi approved these changes

2021-12-01 18:08 UTC, curufinwe approved these changes

2021-12-01 18:09 UTC, merged