add additional docstrings
rwth-i6/i6_core pull request #195
Opened 2021-12-03 15:18 UTC by JackTemaki

Some additional docstrings, open for discussion...

2021-12-06 10:42 UTC, christophmluscher approved these changes

2021-12-06 11:32 UTC, michelwi approved these changes

2021-12-06 11:32 UTC, michelwi commented on meta/system.py
> +        )  # type: Optional[str] # format type of the corpus, see e.g. get_input_node_type()
```suggestion
        )  # type: Optional[str] # format type of the audio files, see e.g. get_input_node_type()
```

2021-12-08 16:44 UTC, curufinwe requested changes

2021-12-08 16:44 UTC, curufinwe commented on rasr/config.py
> +
Maybe a few less newlines

2021-12-08 16:56 UTC, JackTemaki commented on meta/system.py
> +        )  # type: Dict[str,Dict[str,Union[List[rasr.FlagDependentFlowAttribute], rasr.FlagDependentFlowAttribute]]]
I do not know what this could be, so I just put in what makes my IDE happy.

2021-12-08 16:56 UTC, JackTemaki commented on meta/system.py
> +        )  # type: Dict[str,Dict[str,Union[List[rasr.FlagDependentFlowAttribute], rasr.FlagDependentFlowAttribute]]]
If you say it can really be anything, we can put "Any".

2021-12-08 16:58 UTC, JackTemaki commented on meta/system.py
> +            ].out_lattice_bundle,  # noqa, job type is not known
This is for warning suppression in PyCharm, I put this at multiple locations were we are doing kind of "unsafe" access on job outputs which might not exist. 

I think the correct code would be to do an `isinstance` check beforehand for the correct job implementation.

2021-12-08 18:04 UTC, curufinwe commented on meta/system.py
> +        )  # type: Dict[str,Dict[str,Union[List[rasr.FlagDependentFlowAttribute], rasr.FlagDependentFlowAttribute]]]
Let's put Any. To define the correct Union type would be very messy I think.

2021-12-10 11:28 UTC, curufinwe approved these changes

2021-12-10 11:29 UTC, merged