BlissToOggZipJob: allow setting ffmpec_acodec
rwth-i6/i6_core pull request #219
Opened 2022-02-16 16:12 UTC by vieting

The option is already available in the RETURNN script, so just allow to set it in the job.

2022-02-16 16:55 UTC, michelwi requested changes
add to `__sis_hash_exclude__ `

2022-02-16 17:04 UTC, vieting commented
> add to `__sis_hash_exclude__ `

Good point. Done.

2022-02-16 17:44 UTC, michelwi approved these changes

2022-02-18 07:15 UTC, vieting commented
@JackTemaki do you want to comment? Otherwise I'd merge, as @michelwi already reviewed.

2022-02-21 10:47 UTC, JackTemaki approved these changes

2022-02-21 10:48 UTC, merged