Add rqmt dict for BlissToOggZip job
rwth-i6/i6_core pull request #26
Opened 2021-05-12 16:11 UTC by mmz33

this can be used if the dataset is large.

2021-05-12 16:20 UTC, JackTemaki requested changes

2021-05-12 16:20 UTC, JackTemaki commented on returnn/oggzip.py
> +        :param dict[str] rqmt: job's resources requirements dict
type is `dict[str, Any]|None`, also note here that setting this will disable running the job as mini task

2021-05-12 16:20 UTC, JackTemaki commented on returnn/oggzip.py
> +        self.rqmt = rqmt
The default style is to put self.rqmt after the output definitions at the end of the constructor.

2021-05-12 17:25 UTC, curufinwe requested changes

2021-05-12 17:25 UTC, curufinwe commented on returnn/oggzip.py
> +        rqmt=None,
I'd not put the rqmt in the constructor. It's OK to have them set later. (This is the default for many jobs)

2021-05-12 17:25 UTC, curufinwe commented on returnn/oggzip.py
>          yield Task("run", mini_task=True)
This should be in an else branch now.

2021-05-20 09:47 UTC, JackTemaki approved these changes

2021-05-20 16:16 UTC, curufinwe approved these changes

2021-05-20 16:16 UTC, merged