Do not filter out special lemmas.
rwth-i6/i6_core pull request #291
Opened 2022-07-19 13:19 UTC by sarahberanek

Do not filter out special lemmas eg this silence lemma was filtered out after running the FilterJob:
<lemma special="silence"><orth/><phon>si</phon><synt/><eval/></lemma>

2022-07-19 13:42 UTC, michelwi requested changes

2022-07-19 13:48 UTC, michelwi approved these changes
Ok, but please also test my implementation. 🙃

2022-07-19 13:50 UTC, sarahberanek commented
> Ok, but please also test my implementation. upside_down_face

Jup will rerun the whole Lexicon creation from scratch now. Thanks

2022-07-21 11:16 UTC, sarahberanek commented
> Ok, but please also test my implementation. upside_down_face

Worked like a charm.

2022-07-21 12:04 UTC, christophmluscher approved these changes

2022-07-22 08:29 UTC, merged