Add rec_step_by_step options to graph compilation
rwth-i6/i6_core pull request #383
Opened 2023-03-17 16:50 UTC by SimBe195

Add option to specify `rec_step_by_step` layer in `CompileTFGraphJob`. This option is used to compile encoder-decoder models such as RNN-T.

2023-03-20 08:34 UTC, michelwi approved these changes

2023-03-22 13:54 UTC, JackTemaki requested changes

2023-04-12 08:08 UTC, JackTemaki requested changes

2023-04-12 08:08 UTC, JackTemaki commented on returnn/compile.py
> +        self.out_rec_json_info = self.output_path("rec.info")
I think this variable should only be created if the flag is set.

2023-04-19 09:27 UTC, JackTemaki approved these changes

2023-04-19 09:27 UTC, merged