add corrected applicator to linear alignment
rwth-i6/i6_core pull request #407
Opened 2023-05-10 16:29 UTC by christophmluscher

@Marvin84 can I apply this like this to the linear alignment step?

2023-05-10 16:41 UTC, Marvin84 commented
> @Marvin84 can I apply this like this to the linear alignment step?

Looks good.
Once you ran this, please send me your `alignment.config` of the resulting job so that I can double-check.

2023-05-11 06:30 UTC, Atticus1806 commented on am/config.py
> +    :param exit_penalty:
Could you add some docs pls? :)

2023-05-11 06:51 UTC, Atticus1806 commented
I have to be honest. I have no clue :sweat_smile:

2023-05-11 07:44 UTC, Marvin84 commented on am/config.py
> +    :param exit_penalty:
Docs of what type you mean?

2023-05-11 07:46 UTC, Marvin84 commented
> I have to be honest. I have no clue 😅

There is a `rasr` PR for this : https://github.com/rwth-i6/rasr/pull/14

2023-05-11 09:50 UTC, Atticus1806 commented
> There is a rasr PR for this : https://github.com/rwth-i6/rasr/pull/14

Thanks, but I was referring to the python test failing or rather why this only comes up now ^^

2023-05-11 10:02 UTC, Atticus1806 requested changes
So if we bump to 3.8 I would revert the "fix" to make the test run.

2023-05-11 12:25 UTC, Atticus1806 approved these changes

2023-05-11 13:24 UTC, merged