Add alias to am_lm_scale job
rwth-i6/i6_core pull request #419
Opened 2023-06-19 14:52 UTC by Atticus1806

Add alias to am_lm_scale job

2023-06-19 14:55 UTC, JackTemaki requested changes

2023-06-20 09:13 UTC, michelwi reviewed
of cause the aliases can be chosen arbitrarily, but here some suggestions for more consistency.

2023-06-20 09:13 UTC, michelwi commented on meta/system.py
> +        lat2ctm.add_alias("%s%s_conv_to_ctm" % (prefix, name))
We have already 
```
rec.add_alias("%srecog_%s" % (prefix, name))
```
and 
```
self.jobs[corpus]["lat2ctm_%s" % name] = ...
```
so I guess the most consistent formatting would be
```suggestion
        lat2ctm.add_alias("%slat2ctm_%s" % (prefix, name))
```

2023-06-20 09:13 UTC, michelwi commented on meta/system.py
> +        j.add_alias("%s%s_optimize_am_and_lm_scale" % (prefix, name))
same as above
```suggestion
        j.add_alias("%soptimize_%s" % (prefix, name))
```

2023-06-20 09:32 UTC, michelwi approved these changes

2023-06-20 13:28 UTC, christophmluscher approved these changes

2023-06-22 13:33 UTC, merged