Add alias to LMImageAndGlobalCacheJob
rwth-i6/i6_core pull request #420
Opened 2023-06-19 15:00 UTC by Atticus1806

This PR adds an alias to the LMImageAndGlobalCacheJob within the AdvancedTreeSearchJob. I was not really able to find a way to add this without adding a job input and excluding it from hash. Feel free to suggest better ways if possible.

2023-06-20 09:24 UTC, Atticus1806 commented on recognition/advanced_tree_search.py
> +
Oh I did not see that.

2023-06-20 13:27 UTC, christophmluscher reviewed
since you are touching this file it would be nice to update typing and so on :)

2023-06-21 07:26 UTC, christophmluscher approved these changes
thx! :)

IIRC some params can be `float` instead of `int`. otherwise fine.

2023-06-21 07:26 UTC, christophmluscher commented on recognition/advanced_tree_search.py
> +        lmgc_mem: int = 12,
```suggestion
        rtf: float = 10.,
        mem: float = 4.,
        cpu: int = 1,
        lmgc_mem: float = 12.,
```

?

2023-06-21 07:26 UTC, christophmluscher commented on recognition/advanced_tree_search.py
> +        lmgc_mem: int,
```suggestion
        mem: float,
        cpu: int,
        lmgc_mem: float,
```

2023-06-21 07:30 UTC, christophmluscher requested changes
I ll add a comment in a sec

2023-06-21 07:32 UTC, christophmluscher approved these changes
just as a suggestion

2023-06-21 07:57 UTC, merged