add GetBestPtCheckpointJob
rwth-i6/i6_core pull request #432
Opened 2023-07-25 15:32 UTC by vieting

We have the `GetBestTFCheckpointJob` and I'd like to add the equivalent for torch checkpoints. I added a very similar `GetBestPtCheckpointJob` since this does not interfere with existing setups. We might also think about how to avoid some of the code duplications, but this seems to be the simplest solution.

2023-07-25 16:04 UTC, JackTemaki requested changes
I think for PyTorch we can simplify this a little bit more

2023-07-25 16:05 UTC, JackTemaki requested changes
I think for PyTorch we can simplify this a little bit more

2023-07-25 16:24 UTC, vieting commented
> I think for PyTorch we can simplify this a little bit more

Right. In this case, the code duplication is also reduced, so we can just add the torch specific job imho.

2023-07-25 20:17 UTC, JackTemaki approved these changes

2023-07-26 14:31 UTC, michelwi approved these changes

2023-07-26 14:32 UTC, merged