Update perplexity job w lm tool
rwth-i6/i6_core pull request #520
Opened 2024-06-25 13:58 UTC by JJorgeDSIC

Update the `ComputePerplexityJob` to get the new PPL combinations from RASR's log, these are:

- PPL (as before)
- PPL without unknowns
- PPL without considering sentence-end token.
- PPL without unknowns and without considering sentence-end token.
- Other stats such as num unknowns and unknown ratio.

2024-06-25 14:24 UTC, michelwi requested changes

2024-06-25 14:24 UTC, michelwi commented on lm/perplexity.py
> +        self.num_tokens = self.output_var("num-tokens")
Once the Job finished, all output variables should be set. 

In the code below there can be the case, that some of these variables remain unset. I propose either
* add a fallback value here 
* or add else cases below that set some sentinel values

(e.g. 0 or inf, whatever reasonable)

2024-06-26 09:15 UTC, michelwi approved these changes

2024-06-26 14:38 UTC, Icemole approved these changes

2024-06-27 12:57 UTC, merged