add generic feature extraction function
rwth-i6/i6_core pull request #54
Opened 2021-06-15 17:44 UTC by christophmluscher

Adds a function to the meta system class to extract generic features.

2021-06-16 08:55 UTC, michelwi approved these changes

2021-06-16 10:03 UTC, JackTemaki requested changes

2021-06-16 10:03 UTC, JackTemaki commented on meta/system.py
> +        self.feature_flows[corpus][f"uncached_{name}"] = f.feature_dlow
`dlow` does not seem to be correct...

2021-06-16 10:08 UTC, curufinwe requested changes

2021-06-16 10:08 UTC, curufinwe commented on meta/system.py
> +    ):
docstring, especially for the relation between port_name_mapping and name

2021-06-16 10:08 UTC, curufinwe commented on meta/system.py
> +        self, corpus, name, feature_flow, port_name_mapping, prefix="", **kwargs
you could add a default port_name mapping, often the output of a flow network is "features"

2021-06-17 11:06 UTC, curufinwe requested changes

2021-06-17 11:06 UTC, curufinwe commented on meta/system.py
> +                {"features": name}
```suggestion
        :param str port_name: output port of the flow network to use
```

2021-06-17 11:06 UTC, curufinwe commented on meta/system.py
> +                {"features": name}
Now that the user does not specify the port_name_mapping herself it's fine to not explain it anyomore.

2021-06-25 15:26 UTC, merged