Sentence Length Histogram Job
rwth-i6/i6_core pull request #555
Opened 2024-11-14 16:34 UTC by christophmluscher

Job to generate a histogram of the sentence lengths

2024-11-15 08:04 UTC, michelwi requested changes

2024-11-15 08:04 UTC, michelwi commented on text/info.py
> +                ):
if one out of `self.max_words` and `self.max_chars` is not None but the other is, then the first set of parentheses evaluates to True and the second one is evaluated where `some_number > None` will lead to an error. Suggest to transpose the parentheses:
```suggestion
                if (self.max_words is not None and num_words > self.max_words) or (
                    self.max_chars is not None and num_chars > self.max_chars
                ):
```

2024-11-16 09:36 UTC, michelwi approved these changes

2024-12-02 11:38 UTC, JackTemaki approved these changes
I feel the job is very specific, and maybe user would want to adjust the plot (e.g. different bin sizes). One extension idea: you could print the removed lines in a different color or so.

But technically it seems fine, so I guess I can approve.

2024-12-02 11:51 UTC, christophmluscher commented
I would let future users extend this if they want further functionality :D

2024-12-02 11:51 UTC, merged