Fix newline in Bliss corpus orth
rwth-i6/i6_core pull request #560
Opened 2024-12-03 17:02 UTC by Icemole

The actual functionality of the code seems ambiguous with respect to the explanatory comment some lines above.

In order to keep the information from the writing, the newline should be substituted by a space, and not by an empty string. Example:

```
HELLO
WORLD
```

Current functionality: `HELLOWORLD`.

My proposal is consistent with the human way of reading: `HELLO WORLD`.

2024-12-03 17:11 UTC, kuacakuaca approved these changes

2024-12-03 17:23 UTC, albertz reviewed
I wonder if this can break anything else? Should we maybe have a `strip()` at the end?

2024-12-03 17:27 UTC, michelwi commented
How does rasr handle this? I think this lib should follow rasr behavior even if it is not how we expect or want it.

2024-12-04 07:28 UTC, christophmluscher requested changes
I agree with @michelwi this would break older setups. Maybe introduce `V2`?

2024-12-04 07:56 UTC, Atticus1806 requested changes
I agree with the other two, this should not change old existing corpora.

2024-12-04 10:11 UTC, Icemole commented
Hi all, thank you for your answers. I see that there's a lot of (understandable) reservations towards changing this.

For further context, my initial (and only, so far) use case was being able to split words separated by `\n` in the transcription, but then I realized that I could do that when creating the first corpus to begin with, for which I had the control.

Again, thank you all for your feedback. From my side this can be declined so as not to cause further confusion, and apologies for any already caused.

I'll leave the thread open in case the V2 idea has settled on your minds and your heart is now burning with desire of implementing this :smile:

2024-12-09 07:08 UTC, closed without merging

2024-12-09 15:44 UTC, michelwi commented
FYI, I gave it a quick test, and it seems to me that RASR separates words on newlines. So the current implementation is indeed a bug.

2024-12-17 07:48 UTC, Icemole commented
It would then be interesting to see a `CorpusV2` implementation some day. But integrating this in all our jobs would be a very complicated task...