add parameter blacklist to ReturnnTrainingJob
rwth-i6/i6_core pull request #60
Opened 2021-06-21 10:13 UTC by JackTemaki

Setting these parameters directly in the 'returnn_config` leads to incorrect hashes and causes inconsistencies in the dumped config, so doing this should be prohibited.

2021-06-22 09:35 UTC, papar22 approved these changes

2021-06-22 20:32 UTC, christophmluscher approved these changes

2021-06-24 16:47 UTC, michelwi approved these changes

2021-06-25 10:01 UTC, curufinwe requested changes

2021-06-25 10:01 UTC, curufinwe commented on returnn/training.py
> +                key in returnn_config.config or key in returnn_config.post_config
please use config.get() for this instead of manually checking config and post_config

2021-06-25 11:38 UTC, curufinwe approved these changes

2021-06-25 11:38 UTC, merged