Use create_returnn_config to get the hash in the ReturnnSearchJob and ReturnnTrainingJob
rwth-i6/i6_core pull request #63
Opened 2021-06-23 08:58 UTC by dthulke

Alternative to #62 (see the discussion for context)

The output of create_returnn_config is now used to get the hash in the ReturnnSearchJob and ReturnnTrainingJob.
This ensures that all changes made to the config in this method change the hash.

**This will change all hashes of train and search jobs.**

2021-06-23 09:15 UTC, JackTemaki commented
I think this might not be a bad idea, as then there can be no conflicts when trying to override. But we need to make sure that the `config` that is set internally is exactly as we want it to be, so we would need to discuss if `"target": "classes"` needs to be removed, and if 
```        
 "need_data": False,
 "search_do_eval": 0,
```
is still correct.

2021-06-23 09:26 UTC, JackTemaki commented
Also the question would be if still blacklisting is not the better option, because now you can still do user errors. So if you say in the Job parameter `output_mode = "txt"` and in your returnn config `"search_output_file_format": "py"` it will hash "py" correctly, but this still is inconsistent...

2021-06-23 09:57 UTC, christophmluscher commented
> But we need to make sure that the config that is set internally is exactly as we want it to be

I agree.

> because now you can still do user errors

IMHO the most important part is that the config actually used in training/search is used to compute the hash. So that change in search always results in a different hash. David showed this is not the case.

Additionally, I think it is good to enforce that the user gets what she expects. So blacklist and/or warning system would be useful in this case.

2021-06-23 09:59 UTC, JackTemaki commented
> Additionally, I think it is good to enforce that the user gets what she expects. So blacklist and/or warning system would be useful in this case.

Okay, so we do all, fix the hash here, add a config consistency check (I already started code for this) and add the parameter blacklist.

2021-06-23 10:10 UTC, JackTemaki requested changes
Please also fix this for the hash function in ReturnnRasrTrainingJob

2021-06-23 10:16 UTC, JackTemaki commented
Also see #64

2021-06-23 11:58 UTC, dthulke commented
> Please also fix this for the hash function in ReturnnRasrTrainingJob

Done

2021-06-25 15:21 UTC, curufinwe approved these changes

2021-06-25 15:22 UTC, merged