Set bellman-ford as the default best path algorithm
rwth-i6/i6_core pull request #65
Opened 2021-06-24 14:33 UTC by Marvin84

Differently to Dijkstra, the Bellmann-Ford algorithm operates on graphs with negative edges. This is important for the lattice to ctm conversion job, when we have negative scores.

2021-06-24 15:51 UTC, curufinwe requested changes

2021-06-24 15:51 UTC, curufinwe commented on recognition/conversion.py
> +        best_path_algo="bellman-ford",  # default is dijkstra, which does not work on graphs with negative edge-weights
please remove the comment, it is not relevant anymore ("default" might confuse the reader as the default in this job is now bellman-ford)

2021-06-24 16:14 UTC, michelwi approved these changes

2021-06-25 09:52 UTC, curufinwe approved these changes

2021-06-25 09:52 UTC, merged