allow returnn configs with get_network function
rwth-i6/i6_core pull request #95
Opened 2021-07-14 13:21 UTC by vieting

RETURNN allows using configs which define a function `get_network()` instead of the usual `network`. This should also be allowed in the training job.

2021-07-14 13:27 UTC, michelwi requested changes
No, this should not be allowed, because it directly contradicts our conclusion in #93 that a function name should be unique to what the function does.

So either the function code is hashed or we cannot allow to define the network via a function object.

2021-07-14 13:37 UTC, vieting commented
Well, `network = get_network()` is allowed but leads to exactly the same problem.

2021-07-14 13:40 UTC, vieting commented
So if I use functions, I have to take care of the hash manually anyway.

2021-07-14 13:44 UTC, michelwi commented
There definitively should never be the case that two different trainings with different network structures have the same hash.

> I have to take care of the hash manually anyway.

this is not how it should be. Then we should instead add a check, that the function `get_network()`, if used, is added via a string and not as a function object, such that it is correctly hashed.

2021-07-14 13:47 UTC, JackTemaki commented
This is actually a good point that I did not thing of yet.

In the end we wanted to have a way where we define a "dynamic" (with respect to the epoch) network object in our Sisyphus setup, but then print each "fixed" network into the config file. But for this we actually need to use `get_network()`. I will think of a solution for this, as I will need it anyway for the new TTS construction that my Hiwi is currently implementing.

@vieting if you can wait a little bit, we can discuss this together, and then do a new PR about this.

2021-07-14 13:56 UTC, vieting commented
>There definitively should never be the case that two different trainings with different network structures have the same hash.

I agree, but this contradicts the outcome of the discussion in #93.

> @vieting if you can wait a little bit, we can discuss this together, and then do a new PR about this.

Sure, let's do this :)

2021-07-14 13:59 UTC, michelwi commented
> > There definitively should never be the case that two different trainings with different network structures have the same hash.

> I agree, but this contradicts the outcome of the discussion in #93.

Then we should reopen the discussion or find another solution.

2021-07-16 08:14 UTC, curufinwe commented on returnn/training.py
> +            for obj in returnn_config.python_prolog.values()
also check in python_epilog

2021-08-02 15:23 UTC, vieting commented
I discussed this with @JackTemaki and he'll create a PR with a different solution instead.

2021-08-02 15:23 UTC, closed without merging